### ISSUE TITLE
Daily checklist / TODO list

### ISSUE THREAD

**Issue by baadamczyk** [baadamczyk/WORK_flowenhancer#108]
**Summary**
In order to keep the user productive thourghout the day, let's introduce a list of daily (recurrent on business day basis) task, with reminders that are counted from start of an application.

**Details**
Functionality should work that way, so the task list will show up on a start screen or as a popup upon application startup, or after +8 hours of app inactivity (business day), when the app is active again.
Reminders should be also available (as option). They should work that way, so instead of user specyfying the time on which reminder will show, he will use the measure of **hours/minutes from beginning of a business day** (application startup or application activity after +8 hours inactivity).

**Acceptance criteria**
- [ ] task list popup window / application section is designed propely (simmilar to outlook one)
- [ ] task list is showing on application startup
- [ ] task list is showing when application is activated again after 8+ hours of inactivity (suspended pc)
- [ ] user is able to (optionally) specify a time form the buisiness day start, after which reminder to concrete task will show up
- [ ] buisiness day lenght should be available from the settings menu
- [ ] buisiness days during the week should be possilble to set up from the settings menu
- [ ] code coverage is at least 80%

**Additional context**
TBD
