### ISSUE TITLE
Implement time tracking widget

### ISSUE THREAD

**Issue by baadamczyk** [baadamczyk/WORK_flowenhancer#17]
Widget available from system notification area should be implemented

- [ ] Application icon visible in system notification area
- [ ] Left-clicking on it will display little summary popup (task name/time logged/start & pause buttons)
- [ ] Right-clicking on it will display its context menu (start/pause/finish/change task/close app)
