### ISSUE TITLE
Subtask lists presets

### ISSUE THREAD

**Issue by baadamczyk** [baadamczyk/WORK_flowenhancer#36]
- [ ] User should be able to add subtask list to card from existing preset (ex. post-development steps, sanity checks)
- [ ] User should be able to create his own presets that can be then used in the same way as default ones
- [ ] It should be possible to specific presets that will appear on every new card (default = none) - picklist
